#!/bin/bash
echo "."
echo "├── README.md                         # Setup, run, overview"
echo "├── .env.example                      # DATABASE_URL or path to SQLite"
echo "├── requirements.txt                  # lxml/ElementTree, dateutil, (FastAPI optional)"
echo "├── index.html                        # Dashboard entry (static)"
echo "├── web/"
echo "│   ├── styles.css                    # Dashboard styling"
echo "│   ├── chart_handler.js              # Fetch + render charts/tables"
echo "│   └── assets/                       # Images/icons (optional)"
echo "└── data/"
echo "    ├── raw/                          # Provided XML input (git-ignored)"
echo "    │   └── momo.xml"
echo "    ├── processed/                    # Cleaned/derived outputs for frontend"
echo "    │   └── dashboard.json            # Aggregates the dashboard reads"
echo "    ├── db.sqlite3                    # SQLite DB file"
echo "    └── logs/"
echo "        ├── etl.log                   # Structured ETL logs"
echo "        └── dead_letter/              # Unparsed/ignored XML snippets"
